### ISSUE TITLE
App initiating errors

### ISSUE THREAD

**Issue by pawel2105** [adityab/memecached#1]
I've started Mongod and when I run node app.js, it works, but I get:

user:memebase pawel$ node app.js
   warn  - error raised: Error: listen EADDRINUSE
[TypeError: undefined is not a function]
TypeError: undefined is not a function
    at /Users/pawel/Downloads/memebase/node_modules/mongodb/lib/mongodb/db.js:173:14
    at [object Object].<anonymous> (/Users/pawel/Downloads/memebase/node_modules/mongodb/lib/mongodb/connection/server.js:144:7)
    at [object Object].g (events.js:154:14)
    at [object Object].emit (events.js:88:20)
    at [object Object]._callHandler (/Users/pawel/Downloads/memebase/node_modules/mongodb/lib/mongodb/db.js:756:25)
    at /Users/pawel/Downloads/memebase/node_modules/mongodb/lib/mongodb/connection/server.js:241:32
    at [object Object].parseBody (/Users/pawel/Downloads/memebase/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:121:5)
    at [object Object].<anonymous> (/Users/pawel/Downloads/memebase/node_modules/mongodb/lib/mongodb/connection/server.js:232:24)
    at [object Object].emit (events.js:67:17)
    at [object Object].<anonymous> (/Users/pawel/Downloads/memebase/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:149:13)

**Comment by adityab** [comment]
Hi, this was because there was no error handled in `db.open()`. It works because there is usually no connection error if `mongod` is started.

Fixed now.
